name: kiranjaapp_client
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  country_picker: ^2.0.20
  pinput: ^2.2.31
  image_picker: ^0.8.9
  google_nav_bar: ^5.0.6
  dots_indicator: ^2.1.1
  getwidget: ^3.1.1
  cached_network_image: ^3.2.3
  youtube_player_flutter: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/kiranja-logo.png
    - assets/images/image1.png
    - assets/images/image11.png
    - assets/images/image22.png
    - assets/images/banner.jpg
 

  
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
